### ISSUE TITLE
Data package website not found

### ISSUE THREAD

**Issue by Yiming-Shen** [DiltheyLab/HLA-PRG-LA#12]
Hi Alex,

I was trying to download the data package for HLA-PRG-LA [http://www.well.ox.ac.uk/PRG_MHC_GRCh38_withIMGT.tar.gz](url) and unfortunately got this message:

> Resolving www.well.ox.ac.uk (www.well.ox.ac.uk)... 129.67.44.50
> Connecting to www.well.ox.ac.uk (www.well.ox.ac.uk)|129.67.44.50|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2017-12-07 01:01:03 ERROR 404: Not Found.

It seems that the link to the data package is no longer available. (The same issue happens to the link of HLA-PRG data package [http://www.well.ox.ac.uk/HLA-PRG.tar.gz](url) )
Could you please update the data package link?

**Comment by Yiming-Shen** [comment]
Soory but I just found the original website working again. Thanks anyway.

**Comment by nucleo505** [comment]
Hello, I would like to reopen this issue, I can't locate the data package http://www.well.ox.ac.uk/PRG_MHC_GRCh38_withIMGT.tar.gz  all searches for this package seem to redirect here. please help thanks!

**Comment by AlexanderDilthey** [comment]
We're looking into this right now.

**Comment by AlexanderDilthey** [comment]
This is fixed now. There is new URL in the README. Apologies! There was some restructuring of server architecture going on in the background...

**Comment by admar505** [comment]
These things happen with institutional websites, no worries and thank you for fixing!
