### ISSUE TITLE
Test CRAM files now missing

### ISSUE THREAD

**Issue by adbeggs** [DiltheyLab/HLA-PRG-LA#16]
Hi
Just to flag up the NA12878 CRAM files are gone from the link in README.MD:

https://gembox.cbcb.umd.edu/shared/NA12878.cram

It says the server has been retired??

BW

Andrew

**Comment by AlexanderDilthey** [comment]
Hi Andrew,

Thank you for flagging this - the UMD server was indeed retired. I've replaced the link to the .mini file with a functional URL - will do the same for the complete NA12878 CRAM once I'm behind a decent internet connection :-)

Cheers,

Alex
