### ISSUE TITLE
indexing - error

### ISSUE THREAD

**Issue by Valeriia-arh** [DiltheyLab/HLA-PRG-LA#2]
Hi
I did the indexing with the following command
../bin/HLA-PRG-LA --action prepareGraph --PRG_graph_dir ../graphs/PRG_MHC_GRCh38_withIMGT

It began, but then was killed: 31800000Killed
Please, help, what shall I do?

**Comment by AlexanderDilthey** [comment]
Hi Valeria,

Memory perhaps? Does the machine you're running on have enough RAM? Is there a ulimit -v in effect?
